server:
  port: 8085

spring:
  application:
    name: paymentgateway

gateway:
  secret: ${MOCK_GATEWAY_SECRET}
  webhook-url: ${PAYMENT_SERVICE_WEBHOOK_URL:http://payment-service:8083/api/v1/webhook/topup}

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  level:
    com.gpay: INFO